version: '3.8'

services:
  php-web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - php_nfs:/var/www/html
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

volumes:
  php_nfs:
    driver_opts:
      type: nfs
      o: addr=nfs-server,rw
      device: ":/nfsshare"