version: '3'

networks:
 monreseauprive:
  driver: bridge


services:
  mon_serveur_redis:
   image: redis/redis-stack:latest
   deploy:
       replicas: 3
   volumes:
    - ./dataredis:/data
   environment:
    REDIS_ARGS: "--save 10 1"
   networks:
    - monreseauprive


  mon_site_web_flask:
    image: yannisbre/mon_site_web_flask
    deploy :
        replicas: 3
    ports:
     - 8800:8000
    environment:
      FLASK_ENV: development
    networks:
    - monreseauprive