Vagrant.configure("2") do |config|
  # Configuration commune pour toutes les VM
  config.vm.box = "ubuntu/focal64" # Choix de l'image de base (Ubuntu 20.04)

  # Définition de la première VM
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.101"
    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "VM1"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # Définition de la deuxième VM
  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.102"
    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "VM2"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  # Définition de la troisième VM
  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.56.103"
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "VM3"
      vb.memory = 512
      vb.cpus = 1
    end
  end
end